"""Add verdict field

Revision ID: 04e5cdee36c1
Revises: f4caa3c41469
Create Date: 2025-07-02 13:21:16.486686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04e5cdee36c1'
down_revision: Union[str, None] = 'f4caa3c41469'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phishing_attempts', sa.Column('verdict', sa.String(), nullable=True))
    op.alter_column('phishing_attempts', 'body_preview',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index('ix_phishing_attempts_sender', table_name='phishing_attempts')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_phishing_attempts_sender', 'phishing_attempts', ['sender'], unique=False)
    op.alter_column('phishing_attempts', 'body_preview',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('phishing_attempts', 'verdict')
    # ### end Alembic commands ###
