"""create phishing_attempts table

Revision ID: f4caa3c41469
Revises: 
Create Date: 2025-06-24 15:36:04.138154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4caa3c41469'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phishing_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender', sa.String(length=100), nullable=True),
    sa.Column('subject', sa.String(length=200), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.Column('body_preview', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phishing_attempts_id'), 'phishing_attempts', ['id'], unique=False)
    op.create_index(op.f('ix_phishing_attempts_sender'), 'phishing_attempts', ['sender'], unique=False)
    op.drop_index('ix_phishing_reports_id', table_name='phishing_reports', if_exists=True)
   # op.drop_table('phishing_reports')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phishing_reports',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sender', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('subject', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='phishing_reports_pkey')
    )
    op.create_index('ix_phishing_reports_id', 'phishing_reports', ['id'], unique=False)
    op.drop_index(op.f('ix_phishing_attempts_sender'), table_name='phishing_attempts')
    op.drop_index(op.f('ix_phishing_attempts_id'), table_name='phishing_attempts')
    op.drop_table('phishing_attempts')
    # ### end Alembic commands ###
